/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sporto.ng.gestion_ng;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JLayeredPane;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.FlowLayout;

/**
 *
 * @author sebap
 */
@SpringBootApplication
@ComponentScan("com.sporto.ng.gestion_ng")
public class HomeForm extends javax.swing.JFrame {
	private JMenuBar menuBar;
	private JMenuItem mntmProductos;
	private JMenuItem mntmClientes;
	private JMenuItem mntmPedidos;
	private JPanel altaProducto;
	private JLabel lblFechaDeVencimiento;
	private JLabel lblCodigoLabel;
	private JTextField textFieldCodigo;
	private JTextField textFieldFechaDeVencimiento;
	private JLabel lblDescripcin;
	private JTextField textField;

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        JLayeredPane layeredPane = new JLayeredPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(layeredPane, GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(layeredPane, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        			.addContainerGap())
        );
        
        JPanel panelProductos = new JPanel();
        FlowLayout flowLayout_1 = (FlowLayout) panelProductos.getLayout();
        flowLayout_1.setAlignment(FlowLayout.LEFT);
        panelProductos.setBounds(0, 0, 500, 400);
        layeredPane.add(panelProductos);
        
        altaProducto = new JPanel();
        FlowLayout flowLayout = (FlowLayout) altaProducto.getLayout();
        flowLayout.setAlignment(FlowLayout.TRAILING);
        panelProductos.add(altaProducto);
        
        lblCodigoLabel = new JLabel("Código");
        altaProducto.add(lblCodigoLabel);
        
        textFieldCodigo = new JTextField();
        textFieldCodigo.setColumns(10);
        altaProducto.add(textFieldCodigo);
        
        lblFechaDeVencimiento = new JLabel("Fecha de vencimiento");
        altaProducto.add(lblFechaDeVencimiento);
        
        textFieldFechaDeVencimiento = new JTextField();
        textFieldFechaDeVencimiento.setColumns(10);
        altaProducto.add(textFieldFechaDeVencimiento);
        
        lblDescripcin = new JLabel("Descripción");
        altaProducto.add(lblDescripcin);
        
        textField = new JTextField();
        textField.setColumns(10);
        altaProducto.add(textField);
        getContentPane().setLayout(layout);

        pack();
        
        menuBar = new JMenuBar();
        setJMenuBar(menuBar);
        
        mntmProductos = new JMenuItem("Productos");
        menuBar.add(mntmProductos);
        
        mntmClientes = new JMenuItem("Clientes");
        menuBar.add(mntmClientes);
        
        mntmPedidos = new JMenuItem("Pedidos");
        menuBar.add(mntmPedidos);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
    	SpringApplication.run(HomeForm.class, args);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }
}
