/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sporto.ng.gestion_ng;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JLayeredPane;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.FlowLayout;
import com.jgoodies.forms.layout.FormLayout;
import com.jgoodies.forms.layout.ColumnSpec;
import com.jgoodies.forms.layout.FormSpecs;
import com.jgoodies.forms.layout.RowSpec;
import javax.swing.SwingConstants;

/**
 *
 * @author sebap
 */
@SpringBootApplication
@ComponentScan("com.sporto.ng.gestion_ng")
public class HomeForm extends javax.swing.JFrame {
	private JMenuBar menuBar;
	private JMenuItem mntmProductos;
	private JMenuItem mntmClientes;
	private JMenuItem mntmPedidos;
	private JLabel lblFechaDeVencimiento;
	private JLabel lblCodigoLabel;
	private JTextField textFieldCodigo;
	private JTextField textFieldStock;
	private JLabel lblDescripcin;
	private JTextField textFieldFechaDeVencimiento;
	private JTextField textFieldDescripcion;
	private JLabel lblStock;

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        JLayeredPane layeredPane = new JLayeredPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(layeredPane, GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(layeredPane, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        			.addContainerGap())
        );
        
        JPanel panelProductos = new JPanel();
        panelProductos.setBounds(0, 11, 500, 400);
        layeredPane.add(panelProductos);
        panelProductos.setLayout(new FormLayout(new ColumnSpec[] {
        		FormSpecs.LABEL_COMPONENT_GAP_COLSPEC,
        		ColumnSpec.decode("150px"),
        		FormSpecs.LABEL_COMPONENT_GAP_COLSPEC,
        		ColumnSpec.decode("200px:grow"),},
        	new RowSpec[] {
        		FormSpecs.LINE_GAP_ROWSPEC,
        		RowSpec.decode("20px"),
        		FormSpecs.LINE_GAP_ROWSPEC,
        		RowSpec.decode("20px"),
        		FormSpecs.RELATED_GAP_ROWSPEC,
        		FormSpecs.DEFAULT_ROWSPEC,
        		FormSpecs.RELATED_GAP_ROWSPEC,
        		FormSpecs.DEFAULT_ROWSPEC,
        		FormSpecs.RELATED_GAP_ROWSPEC,
        		FormSpecs.DEFAULT_ROWSPEC,
        		FormSpecs.RELATED_GAP_ROWSPEC,
        		FormSpecs.DEFAULT_ROWSPEC,}));
        
        lblCodigoLabel = new JLabel("Código");
        panelProductos.add(lblCodigoLabel, "2, 2, right, default");
        
        textFieldCodigo = new JTextField();
        textFieldCodigo.setText("Codigo");
        panelProductos.add(textFieldCodigo, "4, 2");
        textFieldCodigo.setColumns(10);
        
        lblFechaDeVencimiento = new JLabel("Fecha de vencimiento");
        panelProductos.add(lblFechaDeVencimiento, "2, 6, right, default");
        
        textFieldFechaDeVencimiento = new JTextField();
        panelProductos.add(textFieldFechaDeVencimiento, "4, 6");
        textFieldFechaDeVencimiento.setColumns(10);
        
        lblStock = new JLabel("Stock");
        panelProductos.add(lblStock, "2, 8, right, default");
        
        textFieldStock = new JTextField();
        panelProductos.add(textFieldStock, "4, 8");
        textFieldStock.setColumns(10);
        
        lblDescripcin = new JLabel("Descripción");
        panelProductos.add(lblDescripcin, "2, 12, right, default");
        
        textFieldDescripcion = new JTextField();
        panelProductos.add(textFieldDescripcion, "4, 12");
        textFieldDescripcion.setColumns(10);
        getContentPane().setLayout(layout);

        pack();
        
        menuBar = new JMenuBar();
        setJMenuBar(menuBar);
        
        mntmProductos = new JMenuItem("Productos");
        menuBar.add(mntmProductos);
        
        mntmClientes = new JMenuItem("Clientes");
        menuBar.add(mntmClientes);
        
        mntmPedidos = new JMenuItem("Pedidos");
        menuBar.add(mntmPedidos);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
    	SpringApplication.run(HomeForm.class, args);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }
}
