/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sporto.ng.gestion_ng.view;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.sporto.ng.gestion_ng.dao.ProductoDao;

/**
 *
 * @author sebap
 */
@Component
public class HomeForm extends javax.swing.JFrame   {
	
	private JPanel panelClientes;
	private JPanel panelProductos;
	private JButton btnNewButton_2;
	private JButton btnNewButton_3;
	private ProductoDao dao;
	private JSeparator separator;

	/**
	 * Creates new form HomeForm
	 */
	@Autowired
	public HomeForm(ProductoDao dao,JPanel panelProductos) {
		this.dao = dao;
		this.panelProductos = panelProductos;
		
		initComponents();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		JLayeredPane layeredPane = new JLayeredPane();
		
				btnNewButton_2 = new JButton("Productos");
				btnNewButton_2.addActionListener(new ActionListener() {
					public void actionPerformed(ActionEvent e) {
						layeredPane.removeAll();
						layeredPane.add(panelProductos);
						layeredPane.repaint();
						layeredPane.revalidate();
					}
				});
		
				btnNewButton_3 = new JButton("Clientes");
				btnNewButton_3.setEnabled(false);
				btnNewButton_3.addActionListener(new ActionListener() {
					public void actionPerformed(ActionEvent e) {
						layeredPane.removeAll();
						layeredPane.add(panelClientes);
						layeredPane.repaint();
						layeredPane.revalidate();
					}
				});
		
		JButton btnNewButton_3_1 = new JButton("Pedidos");
		btnNewButton_3_1.setEnabled(false);
		
		JButton btnNewButton_3_1_1 = new JButton("Caja");
		btnNewButton_3_1_1.setEnabled(false);
		
		JButton btnProveedores = new JButton("Proveedores");
		btnProveedores.setEnabled(false);
		
		JButton btnAdmin = new JButton("Admin");
		btnAdmin.setEnabled(false);
		
		separator = new JSeparator();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(separator, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
							.addComponent(btnNewButton_2)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnNewButton_3, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnNewButton_3_1, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnNewButton_3_1_1, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnProveedores, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnAdmin, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
						.addComponent(layeredPane))
					.addGap(128))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(btnNewButton_2)
						.addComponent(btnNewButton_3)
						.addComponent(btnNewButton_3_1)
						.addComponent(btnNewButton_3_1_1)
						.addComponent(btnProveedores)
						.addComponent(btnAdmin))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(separator, GroupLayout.PREFERRED_SIZE, 2, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addComponent(layeredPane, GroupLayout.PREFERRED_SIZE, 335, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(166, Short.MAX_VALUE))
		);


		
		layeredPane.add(panelProductos);
		layeredPane.setLayout(null);

		

//		panelClientes = new JPanel();
//		panelClientes.setLayout(null);
//		panelClientes.setBounds(0, 0, 646, 334);
//		layeredPane.add(panelClientes);

//		scrollPane_1 = new JScrollPane();
//		scrollPane_1.setBounds(10, 91, 574, 194);
//		panelClientes.add(scrollPane_1);
//
//		textField_1 = new JTextField();
//		textField_1.setColumns(10);
//		textField_1.setBounds(10, 60, 254, 20);
//		panelClientes.add(textField_1);
//
//		lblClientes = new JLabel("Clientes");
//		lblClientes.setFont(new Font("Tahoma", Font.BOLD, 20));
//		lblClientes.setBounds(10, 11, 125, 20);
//		panelClientes.add(lblClientes);
//
//		btnNewButton_1 = new JButton("Buscar");
//		btnNewButton_1.setBounds(277, 59, 89, 23);
//		panelClientes.add(btnNewButton_1);
//
//		btnImportar_1 = new JButton("Importar");
//		btnImportar_1.setBounds(376, 59, 89, 23);
//		panelClientes.add(btnImportar_1);
//
//		btnNuevoProducto_1 = new JButton("Nuevo");
//		btnNuevoProducto_1.setBounds(475, 59, 109, 23);
//		panelClientes.add(btnNuevoProducto_1);
		getContentPane().setLayout(layout);
		setPreferredSize(new Dimension(695, 450));
		pack();
	}// </editor-fold>//GEN-END:initComponents
}
